// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated from products-csv/ by scripts/generate-products.js
// Run: npm run generate-products

import { Category, Gender, Size } from "./filter-config";

export interface Product {
    id: string;
    name: string;
    images: string[];
    category: Category;
    gender?: Gender;
    availableSizes?: Size[];
    price?: number;
    description?: string;
}

export const PRODUCTS: Product[] = [
    {
        id: "BD-0099",
        name: "BD 0099",
        images: ["/products/BD-0099/BD-99-BK.jpg","/products/BD-0099/BD-99-NBL.jpg","/products/BD-0099/BD-99-RPK.jpg"],
        category: "LINGERIE" as Category,
        price: 240,
        description: "Babydoll ; Power Net ; Honey Moon Dress ; Red ; One Size",
    },
    {
        id: "BD-0102",
        name: "BD 0102",
        images: ["/products/BD-0102/BD-102-BK.jpg","/products/BD-0102/BD-102-RD.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Power Net ; Co-Ord Set Babydoll ; Red ; One Size",
    },
    {
        id: "BD-0105",
        name: "BD 0105",
        images: ["/products/BD-0105/BD-105-PK.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Spendex Net ; Pink ; One Size",
    },
    {
        id: "BD-0118",
        name: "BD 0118",
        images: ["/products/BD-0118/BD-0118-BK.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Red ; Forbe Lycra ; Honey Moon Dress One Size",
    },
    {
        id: "BD-0121",
        name: "BD 0121",
        images: ["/products/BD-0121/BD-0121-GD.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; White ; Forbe Lycra ; Premium Baby Doll ; One Size",
    },
    {
        id: "BD-0123",
        name: "BD 0123",
        images: ["/products/BD-0123/BD-123-WH.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; White ; Forbe Lycra ; Premium Baby Doll ; One Size",
    },
    {
        id: "BD-0128",
        name: "BD 0128",
        images: ["/products/BD-0128/BD-0128-RD-BK.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Black ; Spendex Net ; Honey Moon Dress ; One Size",
    },
    {
        id: "BD-0138",
        name: "BD 0138",
        images: ["/products/BD-0138/BD-138-BK.jpg","/products/BD-0138/BD-138-BL.jpg","/products/BD-0138/BD-138-GD.jpg","/products/BD-0138/BD-138-MR.jpg","/products/BD-0138/BD-138-OR.jpg","/products/BD-0138/BD-138-R.BL.jpg","/products/BD-0138/BD-138-RD.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Maroon ; Honey Moon Dress ; Power Net ; One Size",
    },
    {
        id: "BD-0142",
        name: "BD 0142",
        images: ["/products/BD-0142/142-NEW-RD.jpg","/products/BD-0142/BD-0142-P.GR.jpg","/products/BD-0142/BD-0142-RPK.jpg","/products/BD-0142/BD-142-BK.jpg","/products/BD-0142/BD-142-NEW-BK.jpg","/products/BD-0142/BD-142-NEW-PR.jpg","/products/BD-0142/BD-142-PR.jpg","/products/BD-0142/BD-142-RD.jpg","/products/BD-0142/BD-142-RPK.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Red ; Spendex Net ; One Size",
    },
    {
        id: "BD-0143",
        name: "BD 0143",
        images: ["/products/BD-0143/BD-0143-N.BL.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Purple ; Honey Moon Dress ; Forbe Lycra ; One Size",
    },
    {
        id: "BD-0155",
        name: "BD 0155",
        images: ["/products/BD-0155/BD-155-BK.jpg","/products/BD-0155/BD-155-WH.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Black ; Babydoll with Robe ; Spendex Net",
    },
    {
        id: "BD-0159",
        name: "BD 0159",
        images: ["/products/BD-0159/BD-0159-BL.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Blue ; Forbe Lycra ; One Size",
    },
    {
        id: "BD-0240",
        name: "BD 0240",
        images: ["/products/BD-0240/BD-240-GRY.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Grey ; Poly Cotton ; One Size",
    },
    {
        id: "BD-0341",
        name: "BD 0341",
        images: ["/products/BD-0341/BD-0341-BK.jpg","/products/BD-0341/BD-0341-RD.jpg","/products/BD-0341/BD-0341-SBL.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Purple ; Honey Moon Dress ; Power Net ; One Size",
    },
    {
        id: "BD-0367",
        name: "BD 0367",
        images: ["/products/BD-0367/BD-0367-MR.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; White ; Premium Baby Doll ; Power Net",
    },
    {
        id: "BD-0368",
        name: "BD 0368",
        images: ["/products/BD-0368/BD-0368-BK.jpg","/products/BD-0368/BD-0368-RD.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Spendex Net ; Black ; One Size",
    },
    {
        id: "BD-1010",
        name: "BD 1010",
        images: ["/products/BD-1010/BD-1010-BK.jpg","/products/BD-1010/BD-1010-MR.jpg","/products/BD-1010/BD-1010-PK.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Babydoll with Robe ; Pink ; forbe Lycra+satin ; One Size",
    },
    {
        id: "BD-1014",
        name: "BD 1014",
        images: ["/products/BD-1014/BD-1014-BK.jpg","/products/BD-1014/BD-1014-RD.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Red ; Forbe Lycra+ Spendex ; One Size",
    },
    {
        id: "BD-1016",
        name: "BD 1016",
        images: ["/products/BD-1016/BD-1016-BK.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Black ; Honey Moon Dress ; Spendex Net ; One Size",
    },
    {
        id: "BD-1017",
        name: "BD 1017",
        images: ["/products/BD-1017/BD-1017-GD.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Gold ; Co-Ord Set Babydoll ; Forbe Lycra ; One Size",
    },
    {
        id: "BD-1024",
        name: "BD 1024",
        images: ["/products/BD-1024/BD-1024-BK.jpg","/products/BD-1024/BD-1024-GR.jpg","/products/BD-1024/BD-1024-MR.jpg","/products/BD-1024/BD-1024-OR.jpg","/products/BD-1024/BD-1024-YL.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Orange ; Honey Moon Dress ; Power Net ; One Size",
    },
    {
        id: "BD-1027",
        name: "BD 1027",
        images: ["/products/BD-1027/BD-1027-MR.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Premium Baby Doll ; Maroon ; Power Net ; One Size",
    },
    {
        id: "BD-1028",
        name: "BD 1028",
        images: ["/products/BD-1028/BD-1028-BK.jpg","/products/BD-1028/BD-1028-GR.jpg","/products/BD-1028/BD-1028-MR.jpg","/products/BD-1028/BD-1028-NBL.jpg","/products/BD-1028/BD-1028-SBL.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Co-Ord Set Babydoll ; Green ; Power Net ; One Size",
    },
    {
        id: "BD-1036",
        name: "BD 1036",
        images: ["/products/BD-1036/BD-1036-AN.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Animal ; Forbe Lycra ; One Size",
    },
    {
        id: "BD-1039",
        name: "BD 1039",
        images: ["/products/BD-1039/BD-1039-SN-GR.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Animal ; Forbe Lycra ; One Size",
    },
    {
        id: "BD-1062",
        name: "BD 1062",
        images: ["/products/BD-1062/BD-1062-BK.jpg","/products/BD-1062/BD-1062-G.BK.jpg","/products/BD-1062/BD-1062-GR.jpg","/products/BD-1062/BD-1062-GRY.jpg","/products/BD-1062/BD-1062-OR.jpg","/products/BD-1062/BD-1062-PK.jpg","/products/BD-1062/BD-1062-RD.jpg","/products/BD-1062/BD-1062-S.BL.jpg","/products/BD-1062/BD-1062-WH.jpg","/products/BD-1062/BD-1062-YL.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Red ; Forbe Lycra ; Premium Baby Doll ; One Size",
    },
    {
        id: "BD-1063",
        name: "BD 1063",
        images: ["/products/BD-1063/BD-1063TD-BK.jpg"],
        category: "LINGERIE" as Category,
        description: "Babydoll ; Forbe Lycra ; Premium Baby Doll ; One Size",
    },
    {
        id: "BT-028",
        name: "BT 028",
        images: ["/products/BT-028/BT-028-BK.JPG","/products/BT-028/BT-028-BR.JPG","/products/BT-028/BT-028-TN.JPG"],
        category: "BELTS" as Category,
        gender: "WOMEN" as Gender,
        price: 250,
        description: "Synthetic Leather ; brass buckle ; One Size",
    },
    {
        id: "BT-029",
        name: "BT 029",
        images: ["/products/BT-029/BT-029-BK.JPG","/products/BT-029/BT-029-BR.JPG","/products/BT-029/BT-029-TN.JPG"],
        category: "BELTS" as Category,
        gender: "WOMEN" as Gender,
        price: 180,
        description: "Synthetic Leather ; brass buckle ; One Size",
    },
    {
        id: "BT-030",
        name: "BT 030",
        images: ["/products/BT-030/BT-030-GR.JPG","/products/BT-030/BT-030-PK.JPG","/products/BT-030/BT-030-RD.JPG","/products/BT-030/BT-030-WH.JPG"],
        category: "BELTS" as Category,
        gender: "WOMEN" as Gender,
        description: "Synthetic Leather ; brass buckle ; One Size",
    },
    {
        id: "BT-031",
        name: "BT 031",
        images: ["/products/BT-031/BT-031-GR.JPG","/products/BT-031/BT-031-PK.JPG","/products/BT-031/BT-031-RD.JPG","/products/BT-031/BT-031-WH.JPG"],
        category: "BELTS" as Category,
        gender: "WOMEN" as Gender,
        description: "Synthetic Leather ; brass buckle ; One Size",
    },
    {
        id: "BT-032",
        name: "BT 032",
        images: ["/products/BT-032/BT-032-BL.JPG","/products/BT-032/BT-032-GR.JPG","/products/BT-032/BT-032-PK.JPG","/products/BT-032/BT-032-RD.JPG","/products/BT-032/BT-032-WH.JPG"],
        category: "BELTS" as Category,
        gender: "WOMEN" as Gender,
        description: "Synthetic Leather ; brass buckle ; One Size",
    },
    {
        id: "BT-033",
        name: "BT 033",
        images: ["/products/BT-033/BT-033-BL.JPG","/products/BT-033/BT-033-GR.JPG","/products/BT-033/BT-033-PK.JPG","/products/BT-033/BT-033-RD.JPG","/products/BT-033/BT-033-WH.JPG"],
        category: "BELTS" as Category,
        gender: "WOMEN" as Gender,
        description: "Synthetic Leather ; brass buckle ; One Size",
    },
    {
        id: "FW-25BK",
        name: "FW 25BK",
        images: ["/products/FW-25BK/25-BK-01.jpg","/products/FW-25BK/25-BK-02.jpg","/products/FW-25BK/25-BK-03.jpg","/products/FW-25BK/25-BK-04.jpg","/products/FW-25BK/25-BK-05.jpg","/products/FW-25BK/25-BK-06.jpg","/products/FW-25BK/25-BK-07.jpg","/products/FW-25BK/25-BK-08.jpg","/products/FW-25BK/25-BK-09.jpg","/products/FW-25BK/25-BK-10.jpg","/products/FW-25BK/25-BK-11.jpg","/products/FW-25BK/25-BK-12.jpg","/products/FW-25BK/25-BK-13.jpg"],
        category: "WATCHES" as Category,
        gender: "KIDS" as Gender,
        price: 200,
        description: "Black Metal Dial ; Sillicone Strap ; Round Analog ; Boys and Girls Watch",
    },
    {
        id: "FW-25SL",
        name: "FW 25SL",
        images: ["/products/FW-25SL/25-SL-01.jpg","/products/FW-25SL/25-SL-02.jpg","/products/FW-25SL/25-SL-03.jpg","/products/FW-25SL/25-SL-04.jpg","/products/FW-25SL/25-SL-05.jpg","/products/FW-25SL/25-SL-06.jpg","/products/FW-25SL/25-SL-07.jpg","/products/FW-25SL/25-SL-08.jpg","/products/FW-25SL/25-SL-09.jpg","/products/FW-25SL/25-SL-10.jpg","/products/FW-25SL/25-SL-11.jpg","/products/FW-25SL/25-SL-12.jpg","/products/FW-25SL/25-SL-13.jpg","/products/FW-25SL/25-SL-14.jpg","/products/FW-25SL/25-SL-15.jpg","/products/FW-25SL/25-SL-16.jpg","/products/FW-25SL/25-SL-17.jpg","/products/FW-25SL/25-SL-18.jpg"],
        category: "WATCHES" as Category,
        gender: "KIDS" as Gender,
        price: 200,
        description: "Silver Metal Dial ; Sillicone Strap ; Round Analog ; Boys and Girls Watch",
    },
    {
        id: "FW-2133",
        name: "FW 2133",
        images: ["/products/FW-2133/2133-PK.jpg","/products/FW-2133/2133-S.BL.jpg"],
        category: "WATCHES" as Category,
        gender: "KIDS" as Gender,
        price: 200,
        description: "Pink Plastic Dial ; Sillicone Strap, Round Analog ; Boys and Girls Watch",
    },
    {
        id: "FW-2139",
        name: "FW 2139",
        images: ["/products/FW-2139/2139-BK.jpg","/products/FW-2139/2139-OR.jpg"],
        category: "WATCHES" as Category,
        gender: "KIDS" as Gender,
        price: 200,
        description: "Black Plastic Dial ; Sillicone Strap, Round Analog ; Boys and Girls Watch",
    },
    {
        id: "FW-2206",
        name: "FW 2206",
        images: ["/products/FW-2206/2206-BK.jpg","/products/FW-2206/2206-BL.jpg","/products/FW-2206/2206-GR.jpg","/products/FW-2206/2206-PK.jpg","/products/FW-2206/2206-PR.jpg","/products/FW-2206/2206-WH.jpg"],
        category: "WATCHES" as Category,
        gender: "KIDS" as Gender,
        price: 200,
        description: "Blue Plastic Dial ; Sillicone Strap, Round Analog ; Boys and Girls Watch",
    },
    {
        id: "FW-2217",
        name: "FW 2217",
        images: ["/products/FW-2217/2217-N.BL.jpg","/products/FW-2217/2217-PR.jpg","/products/FW-2217/2217-PTBL.jpg","/products/FW-2217/2217-PTGR.jpg","/products/FW-2217/2217-PTPK.jpg"],
        category: "WATCHES" as Category,
        gender: "KIDS" as Gender,
        price: 200,
        description: "Blue Plastic Dial ; Sillicone Strap, Round Analog ; Boys and Girls Watch",
    },
    {
        id: "FW-2226",
        name: "FW 2226",
        images: ["/products/FW-2226/2226-BK.jpg","/products/FW-2226/2226-PK.jpg","/products/FW-2226/2226-PR.jpg"],
        category: "WATCHES" as Category,
        gender: "KIDS" as Gender,
        price: 200,
        description: "Black Plastic Dial ; Sillicone Strap, Round Analog ; Boys and Girls Watch",
    },
    {
        id: "FW-9002",
        name: "FW 9002",
        images: ["/products/FW-9002/9002-OR.jpg","/products/FW-9002/9002-PK.jpg","/products/FW-9002/9002-RD.jpg"],
        category: "WATCHES" as Category,
        gender: "KIDS" as Gender,
        price: 200,
        description: "Orange Plastic Dial ; Sillicone Strap, Round Analog ; Boys and Girls Watch",
    },
    {
        id: "SDC-047",
        name: "SDC 047",
        images: ["/products/SDC-047/47-BK-BK.JPG","/products/SDC-047/47-BK-WH.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 215,
        description: "Black dial ; Black case ; Black strap ; Metal alloy case ; Stainless steel strap ; Quartz ; Metal link bracelet ; Fold-over clasp with safety lock",
    },
    {
        id: "SDC-048",
        name: "SDC 048",
        images: ["/products/SDC-048/48-GD-BK.JPG","/products/SDC-048/48-GD-YL.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 215,
        description: "Black dial ; Gold case ; Gold strap ; Metal alloy case ; Stainless steel strap ; Quartz ; Metal link bracelet ; Fold-over clasp with safety lock",
    },
    {
        id: "SDC-088",
        name: "SDC 088",
        images: ["/products/SDC-088/SDC-88-GR.JPG"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver dial ; Black case ; Green strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-089",
        name: "SDC 089",
        images: ["/products/SDC-089/SDC-89-RD.JPG"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "White dial ; Black case ; Red strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-090",
        name: "SDC 090",
        images: ["/products/SDC-090/SDC-90-GRY.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Grey dial ; Black case ; Grey strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-091",
        name: "SDC 091",
        images: ["/products/SDC-091/SDC-91-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Grey dial ; Black case ; Black strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-092",
        name: "SDC 092",
        images: ["/products/SDC-092/SDC-92-GRY.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver dial ; Black case ; Grey strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-093",
        name: "SDC 093",
        images: ["/products/SDC-093/SDC-93-BL.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black dial ; Black case ; Blue strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-094",
        name: "SDC 094",
        images: ["/products/SDC-094/SDC-94-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Grey dial ; Black case ; Black strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-095",
        name: "SDC 095",
        images: ["/products/SDC-095/SDC-95-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Grey dial ; Black case ; Black strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-096",
        name: "SDC 096",
        images: ["/products/SDC-096/SDC-96-GRY.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "White dial ; Black case ; Grey strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-097",
        name: "SDC 097",
        images: ["/products/SDC-097/SDC-97-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Grey dial ; Black case ; Black strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-098",
        name: "SDC 098",
        images: ["/products/SDC-098/SDC-98-BL.JPG"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Blue dial ; Black case ; Blue strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-099",
        name: "SDC 099",
        images: ["/products/SDC-099/SDC-99-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Grey dial ; Black case ; Black strap ; Metal alloy case ; Silicone strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-102",
        name: "SDC 102",
        images: ["/products/SDC-102/SDC-102-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black dial ; Silver case ; Silver strap ; Metal alloy case ; Stainless steel strap ; Quartz ; Metal link bracelet ; Fold-over clasp",
    },
    {
        id: "SDC-111",
        name: "SDC 111",
        images: ["/products/SDC-111/SDC-111-BR.JPG"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "White dial ; Rose gold case ; Brown strap ; Metal alloy case ; Leather strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-112",
        name: "SDC 112",
        images: ["/products/SDC-112/SDC-112-BL.JPG"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Blue dial ; Rose gold case ; Blue strap ; Metal alloy case ; Leather strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-113",
        name: "SDC 113",
        images: ["/products/SDC-113/SDC-113-BK.JPG"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black dial ; Rose gold case ; Black strap ; Metal alloy case ; Leather strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-114",
        name: "SDC 114",
        images: ["/products/SDC-114/SDC-114-BK.JPG"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black dial ; Silver case ; Black strap ; Metal alloy case ; Leather strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-116",
        name: "SDC 116",
        images: ["/products/SDC-116/SDC-116-TN.JPG"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Blue dial ; Silver case ; Tan strap ; Metal alloy case ; Leather strap ; Quartz ; Strap with pin buckle",
    },
    {
        id: "SDC-168",
        name: "SDC 168",
        images: ["/products/SDC-168/SDC-168-BK.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black dial ; Black case ; Black strap ; Metal alloy case ; Stainless steel strap ; Quartz ; Metal link bracelet ; Fold-over clasp",
    },
    {
        id: "SDC-169",
        name: "SDC 169",
        images: ["/products/SDC-169/SDC-169-BK.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black dial ; Black case with rose-gold bezel ; Black strap ; Metal alloy case ; Stainless steel strap ; Quartz movement ; Day & date display ; Fold-over clasp",
    },
    {
        id: "SDC-170",
        name: "SDC 170",
        images: ["/products/SDC-170/SDC-170-BK.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "White dial ; Black case with rose-gold bezel ; Black strap ; Metal alloy case ; Stainless steel strap ; Quartz movement ; Day & date display ; Fold-over clasp",
    },
    {
        id: "SDC-171",
        name: "SDC 171",
        images: ["/products/SDC-171/SDC-171-BK.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black & Rose Gold ; Stainless Steel ; Quartz ; Black Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-172",
        name: "SDC 172",
        images: ["/products/SDC-172/SDC-172-RG-SL.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver & Rose Gold ; Stainless Steel ; Quartz ; Two-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-173",
        name: "SDC 173",
        images: ["/products/SDC-173/SDC-173-BK.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black & Rose Gold ; Stainless Steel ; Quartz ; Black Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-174",
        name: "SDC 174",
        images: ["/products/SDC-174/SDC-174-GR.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Green & Silver & Rose Gold ; Stainless Steel ; Quartz ; Two-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-175",
        name: "SDC 175",
        images: ["/products/SDC-175/SDC-175-RG-SL.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Green & White & Silver & Rose Gold ; Stainless Steel ; Quartz ; Two-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-176",
        name: "SDC 176",
        images: ["/products/SDC-176/SDC-176-BL.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black & Blue ; Stainless Steel ; Quartz ; Black Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-178",
        name: "SDC 178",
        images: ["/products/SDC-178/SDC-178-BK.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black & Rose Gold ; Stainless Steel ; Quartz ; Black Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-179",
        name: "SDC 179",
        images: ["/products/SDC-179/SDC-179-BK.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black & Rose Gold ; Stainless Steel ; Quartz ; Black Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-180",
        name: "SDC 180",
        images: ["/products/SDC-180/SDC-180-BK.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black ; Stainless Steel ; Quartz ; Black Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-181",
        name: "SDC 181",
        images: ["/products/SDC-181/SDC-181-GR.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Green & Black ; Stainless Steel ; Quartz ; Black Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-182",
        name: "SDC 182",
        images: ["/products/SDC-182/SDC-182-BK.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black & Rose Gold ; Stainless Steel ; Quartz ; Black Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-183",
        name: "SDC 183",
        images: ["/products/SDC-183/SDC-183-SL.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver & Black & White ; Stainless Steel ; Quartz ; Silver Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-184",
        name: "SDC 184",
        images: ["/products/SDC-184/SDC-184-SL-GD.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver & Gold & Black & White ; Stainless Steel ; Quartz ; Two-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-185",
        name: "SDC 185",
        images: ["/products/SDC-185/SDC-185-RG-SL.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver & Rose Gold & Black & White ; Stainless Steel ; Quartz ; Two-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-186",
        name: "SDC 186",
        images: ["/products/SDC-186/SDC-186-GD.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Gold & Black ; Stainless Steel ; Quartz ; Gold-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-187",
        name: "SDC 187",
        images: ["/products/SDC-187/SDC-187-BK.jpg","/products/SDC-187/SDC-187-GD.png"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Gold & Black ; Stainless Steel ; Quartz ; Gold-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-188",
        name: "SDC 188",
        images: ["/products/SDC-188/SDC-188-WH.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver & Rose Gold ; Stainless Steel ; Quartz ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-189",
        name: "SDC 189",
        images: ["/products/SDC-189/SDC-189-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver & Black ; Stainless Steel ; Quartz ; Black Dial ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-190",
        name: "SDC 190",
        images: ["/products/SDC-190/SDC-190-WH.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver & White ; Stainless Steel ; Quartz ; White Textured Dial with Gold-Tone Markers ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-191",
        name: "SDC 191",
        images: ["/products/SDC-191/SDC-191-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver & Black ; Stainless Steel ; Quartz ; Black Textured Dial with Gold-Tone Markers & Numerals ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-192",
        name: "SDC 192",
        images: ["/products/SDC-192/SDC-192-SL.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver ; Stainless Steel ; Quartz ; Silver Sunray Dial with Red Accents & Applied Numerals ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-193",
        name: "SDC 193",
        images: ["/products/SDC-193/SDC-193-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver ; Stainless Steel ; Quartz ; Black Dial with Red Accents & Applied Numerals ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-194",
        name: "SDC 194",
        images: ["/products/SDC-194/SDC-194-SL.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver ; Stainless Steel ; Quartz ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-195",
        name: "SDC 195",
        images: ["/products/SDC-195/SDC-195-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black ; Stainless Steel ; Quartz ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-196",
        name: "SDC 196",
        images: ["/products/SDC-196/SDC-196-WH.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "White ; Stainless Steel ; Quartz ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-197",
        name: "SDC 197",
        images: ["/products/SDC-197/SDC-197-BK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black ; Stainless Steel ; Quartz ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-203",
        name: "SDC 203",
        images: ["/products/SDC-203/SDC-203-GBK.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Black ; Stainless Steel ; Quartz ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "SDC-204",
        name: "SDC 204",
        images: ["/products/SDC-204/SDC-204-GWH.jpg"],
        category: "WATCHES" as Category,
        gender: "MEN" as Gender,
        price: 315,
        description: "Silver / White ; Stainless Steel ; Quartz ; Silver-Tone Metal Bracelet with Fold-Over Clasp",
    },
    {
        id: "FL-0935",
        name: "FL 0935",
        images: ["/products/FL-0935/935 DC-1.jpg","/products/FL-0935/936 DC-2.jpg","/products/FL-0935/936 DC-3.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Black Lens ; Square Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FL-1001",
        name: "FL 1001",
        images: ["/products/FL-1001/DC1001-01.jpg","/products/FL-1001/DC1001-02.jpg","/products/FL-1001/DC1001-03.jpg","/products/FL-1001/DC1001-04.jpg","/products/FL-1001/DC1001-05.jpg","/products/FL-1001/DC1001-06.jpg","/products/FL-1001/DC1001-07.jpg","/products/FL-1001/DC1001-08.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Black Lens ; Square Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FL-6087",
        name: "FL 6087",
        images: ["/products/FL-6087/6087-02.jpg","/products/FL-6087/6087-03.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Brown Lens ; Rectangular Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FL-8121",
        name: "FL 8121",
        images: ["/products/FL-8121/8121-01.jpg","/products/FL-8121/8121-02.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Brown Lens ; Oval Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FL11910",
        name: "FL11910",
        images: ["/products/FL11910/11910-01.jpg","/products/FL11910/11910-02.jpg","/products/FL11910/11910-03.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Black Lens ; Oval Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FL22908",
        name: "FL22908",
        images: ["/products/FL22908/22908-01.jpg","/products/FL22908/22908-02.jpg","/products/FL22908/22908-03.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Brown Lens ; Square Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FL23012",
        name: "FL23012",
        images: ["/products/FL23012/23012-01.jpg","/products/FL23012/23012-02.jpg","/products/FL23012/23012-03.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Grey Lens ; Retro-Square Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FL86744",
        name: "FL86744",
        images: ["/products/FL86744/86744-03.jpg","/products/FL86744/86744-04.jpg","/products/FL86744/86744-05.jpg","/products/FL86744/86744-07.jpg","/products/FL86744/86744-08.jpg","/products/FL86744/86744-2.jpg","/products/FL86744/86744-6.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Brown Lens ; Retro-Square Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FL86984",
        name: "FL86984",
        images: ["/products/FL86984/86984-01.jpg","/products/FL86984/86984-04.jpg","/products/FL86984/86984-05.jpg","/products/FL86984/86984-07.jpg","/products/FL86984/86984-2.jpg","/products/FL86984/86984-3.jpg","/products/FL86984/86984-6.jpg","/products/FL86984/86984-8.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Brown Lens ; Oversized Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FL87017",
        name: "FL87017",
        images: ["/products/FL87017/87017-01.jpg","/products/FL87017/87017-02.jpg","/products/FL87017/87017-03.jpg","/products/FL87017/87017-04.jpg","/products/FL87017/87017-05.jpg","/products/FL87017/87017-06.jpg","/products/FL87017/87017-07.jpg","/products/FL87017/87017-08.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Brown Lens ; Oval Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FL240703",
        name: "FL240703",
        images: ["/products/FL240703/240703.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Grey Lens ; Retro-Square Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "FLB1024",
        name: "FLB1024",
        images: ["/products/FLB1024/B1024-01.jpg","/products/FLB1024/B1024-02.jpg","/products/FLB1024/B1024-03.jpg","/products/FLB1024/B1024-04.jpg","/products/FLB1024/B1024-05.jpg","/products/FLB1024/B1024-06.jpg","/products/FLB1024/B1024-07.jpg"],
        category: "SUNGLASSES" as Category,
        gender: "UNISEX" as Gender,
        price: 120,
        description: "Grey Lens ; Retro-Square Sunglass ; Plastic Frame ; Free Size",
    },
    {
        id: "KLW-001",
        name: "KLW 001",
        images: ["/products/KLW-001/KLW-001-BR.jpg"],
        category: "WALLETS" as Category,
        gender: "MEN" as Gender,
        price: 180,
        description: "Brown Synthetic Leather ; Available Cardslot ; Coins Pocket ; One Size",
    },
    {
        id: "KLW-002",
        name: "KLW 002",
        images: ["/products/KLW-002/KLW-002-BK.jpg"],
        category: "WALLETS" as Category,
        gender: "MEN" as Gender,
        price: 180,
        description: "Black Synthetic Leather ; Available Cardslot ; Coins Pocket ; One Size",
    },
    {
        id: "KLW-003",
        name: "KLW 003",
        images: ["/products/KLW-003/KLW-003-BK.jpg"],
        category: "WALLETS" as Category,
        gender: "MEN" as Gender,
        price: 180,
        description: "Black Synthetic Leather ; Available Cardslot ; Coins Pocket ; One Size",
    },
    {
        id: "KLW-004",
        name: "KLW 004",
        images: ["/products/KLW-004/KLW-004-BK.jpg"],
        category: "WALLETS" as Category,
        gender: "MEN" as Gender,
        price: 180,
        description: "Black Synthetic Leather ; Available Cardslot ; Coins Pocket ; One Size",
    },
    {
        id: "KLW-005",
        name: "KLW 005",
        images: ["/products/KLW-005/KLW-005-BR.jpg"],
        category: "WALLETS" as Category,
        gender: "MEN" as Gender,
        price: 180,
        description: "Brown Synthetic Leather ; Available Cardslot ; Coins Pocket ; One Size",
    },
    {
        id: "KLW-006",
        name: "KLW 006",
        images: ["/products/KLW-006/KLW-006-BR.jpg"],
        category: "WALLETS" as Category,
        gender: "MEN" as Gender,
        price: 180,
        description: "Brown Synthetic Leather ; Available Cardslot ; Coins Pocket ; One Size",
    },
    {
        id: "KLW-007",
        name: "KLW 007",
        images: ["/products/KLW-007/KLW-007-TN.jpg"],
        category: "WALLETS" as Category,
        gender: "MEN" as Gender,
        price: 180,
        description: "Tan Synthetic Leather ; Available Cardslot ; Coins Pocket ; One Size",
    },
    {
        id: "KLW-008",
        name: "KLW 008",
        images: ["/products/KLW-008/KLW-008-TN.jpg"],
        category: "WALLETS" as Category,
        gender: "MEN" as Gender,
        price: 180,
        description: "Tan Synthetic Leather ; Available Cardslot ; Coins Pocket ; One Size",
    },
    {
        id: "KLW-009",
        name: "KLW 009",
        images: ["/products/KLW-009/KLW-009-TN.jpg"],
        category: "WALLETS" as Category,
        gender: "MEN" as Gender,
        price: 180,
        description: "Tan Synthetic Leather ; Available Cardslot ; Coins Pocket ; One Size",
    },
    {
        id: "LV-701",
        name: "LV 701",
        images: ["/products/LV-701/LV-701-BK.jpg","/products/LV-701/LV-701-BR.jpg","/products/LV-701/LV-701-RG.jpg","/products/LV-701/LV-701-SL.jpg"],
        category: "WATCHES" as Category,
        gender: "WOMEN" as Gender,
        price: 250,
        description: "Rose Gold ; Analog / Fashion Watch ; Metal alloy ; Stainless steel mesh ; Adjustable sliding clasp",
    },
    {
        id: "LV-702",
        name: "LV 702",
        images: ["/products/LV-702/LV-702-BK.jpg","/products/LV-702/LV-702-GR.jpg","/products/LV-702/LV-702-RG.jpg","/products/LV-702/LV-702-SL.jpg"],
        category: "WATCHES" as Category,
        gender: "WOMEN" as Gender,
        price: 250,
        description: "Rose Gold ; Analog / Fashion Watch ; Metal alloy with rose-gold finish ; Stainless steel link bracelet ; Quartz",
    },
    {
        id: "LV-703",
        name: "LV 703",
        images: ["/products/LV-703/LV-703-BK.jpg","/products/LV-703/LV-703-RG.jpg","/products/LV-703/LV-703-SL.jpg"],
        category: "WATCHES" as Category,
        gender: "WOMEN" as Gender,
        price: 250,
        description: "Rose Gold ; Analog / Fashion Watch ; Metal alloy with rose-gold finish ; Stainless steel link bracelet ; Quartz",
    },
    {
        id: "LV-704",
        name: "LV 704",
        images: ["/products/LV-704/LV-704-BL.jpg","/products/LV-704/LV-704-RG.jpg"],
        category: "WATCHES" as Category,
        gender: "WOMEN" as Gender,
        price: 250,
        description: "Royal Blue ; Analog / Fashion Watch ; Metal alloy with rose-gold finish ; Battery-operated ; Fold-over clasp with safety",
    },
    {
        id: "LV-705",
        name: "LV 705",
        images: ["/products/LV-705/LV-705-BK.jpg","/products/LV-705/LV-705-RG.jpg","/products/LV-705/LV-705-WH.jpg"],
        category: "WATCHES" as Category,
        gender: "WOMEN" as Gender,
        price: 250,
        description: "Black ; Analog / Fashion Watch ; Metal alloy with rose-gold finish ; Battery-operated ; Fold-over clasp with safety",
    },
    {
        id: "LV-706",
        name: "LV 706",
        images: ["/products/LV-706/LV-706-BL.jpg","/products/LV-706/LV-706-GR.jpg","/products/LV-706/LV-706-RG.jpg","/products/LV-706/LV-706-SL.jpg"],
        category: "WATCHES" as Category,
        gender: "WOMEN" as Gender,
        price: 250,
        description: "Teal Blue ; Metal alloy with rose-gold finish ; Stainless steel patterned link bracelet ; Battery-operated ; Fold-over clasp with safety lock",
    },
    {
        id: "LV-707",
        name: "LV 707",
        images: ["/products/LV-707/LV-707-BL.jpg","/products/LV-707/LV-707-SL.jpg"],
        category: "WATCHES" as Category,
        gender: "WOMEN" as Gender,
        price: 250,
        description: "Royal Blue ; Metal alloy with rose-gold finish ; Stainless steel link bracelet ; Battery-operated ; Fold-over clasp with safety lock",
    },
    {
        id: "LV-708",
        name: "LV 708",
        images: ["/products/LV-708/LV-708-BL.jpg","/products/LV-708/LV-708-SL.jpg"],
        category: "WATCHES" as Category,
        gender: "WOMEN" as Gender,
        price: 250,
        description: "Royal Blue ; Metal alloy with rose-gold finish ; Stainless steel link bracelet with black coating ; Quartz ; Fold-over clasp with safety lock",
    },
    {
        id: "LV-709",
        name: "LV 709",
        images: ["/products/LV-709/LV-709-BK.jpg","/products/LV-709/LV-709-SL.jpg"],
        category: "WATCHES" as Category,
        gender: "WOMEN" as Gender,
        price: 250,
        description: "Black ; Metal alloy with rose-gold plating ; Stainless steel link bracelet ; Battery operated ; Fold-over clasp with safety",
    }
];

// Filter products by criteria
export function filterProducts(
    products: Product[],
    categories?: Category[],
    genders?: Gender[],
    sizes?: Size[]
): Product[] {
    return products.filter((product) => {
        if (categories && categories.length > 0) {
            const hasAll = categories.includes("ALL");
            if (!hasAll && !categories.includes(product.category)) {
                return false;
            }
        }

        if (genders && genders.length > 0 && product.gender) {
            if (!genders.includes(product.gender)) return false;
        }

        if (sizes && sizes.length > 0 && product.availableSizes) {
            const hasOverlap = sizes.some(s => product.availableSizes?.includes(s));
            if (!hasOverlap) return false;
        }

        return true;
    });
}
