export interface Product {
    id: string;
    name: string;
    price: number;
    image: string;
    category: "MENS" | "WOMENS" | "ACCESSORIES";
}

export const PRODUCTS: Product[] = [
    {
        id: "YS-01-101",
        name: "PRODUCT YS-01",
        price: 200,
        image: "/assets/extracted/images/img_101_YS-01_101.webp",
        category: "MENS",
    },
    {
        id: "PK-01-103",
        name: "PARKA PK-01",
        price: 770,
        image: "/assets/extracted/images/img_103_PK-01_103.webp",
        category: "MENS",
    },
    {
        id: "BD-10-105",
        name: "BODYSUIT BD-10",
        price: 200,
        image: "/assets/extracted/images/img_105_BD-10_105.webp",
        category: "WOMENS",
    },
    {
        id: "WJ-02-107",
        name: "WORK JACKET WJ-02",
        price: 530,
        image: "/assets/extracted/images/img_107_WJ-02_107.webp",
        category: "MENS",
    },
    {
        id: "PT-05-109",
        name: "PANTS PT-05",
        price: 220,
        image: "/assets/extracted/images/img_109_PT-05_109.webp",
        category: "MENS",
    },
    {
        id: "PT-10-111",
        name: "PANTS PT-10",
        price: 280,
        image: "/assets/extracted/images/img_111_PT-10_111.webp",
        category: "MENS",
    },
    {
        id: "LG-14-113",
        name: "LEGGINGS LG-14",
        price: 250,
        image: "/assets/extracted/images/img_113_LG-14_113.webp",
        category: "WOMENS",
    },
    {
        id: "BX-01-115",
        name: "PRODUCT BX-01",
        price: 200,
        image: "/assets/extracted/images/img_115_BX-01_115.webp",
        category: "MENS",
    },
    {
        id: "HT-04-117",
        name: "HAT HT-04",
        price: 200,
        image: "/assets/extracted/images/img_117_HT-04_117.webp",
        category: "ACCESSORIES",
    },
    {
        id: "BG-01-119",
        name: "BAG BG-01",
        price: 200,
        image: "/assets/extracted/images/img_119_BG-01_119.webp",
        category: "ACCESSORIES",
    },
    {
        id: "SG-03-11",
        name: "PRODUCT SG-03",
        price: 200,
        image: "/assets/extracted/images/img_11_SG-03_11.webp",
        category: "MENS",
    },
    {
        id: "WJ-01-121",
        name: "WORK JACKET WJ-01",
        price: 740,
        image: "/assets/extracted/images/img_121_WJ-01_121.webp",
        category: "MENS",
    },
    {
        id: "PK-01-123",
        name: "PARKA PK-01",
        price: 580,
        image: "/assets/extracted/images/img_123_PK-01_123.webp",
        category: "MENS",
    },
    {
        id: "WH-01-125",
        name: "PRODUCT WH-01",
        price: 200,
        image: "/assets/extracted/images/img_125_WH-01_125.webp",
        category: "MENS",
    },
    {
        id: "YS-01-127",
        name: "PRODUCT YS-01",
        price: 200,
        image: "/assets/extracted/images/img_127_YS-01_127.webp",
        category: "MENS",
    },
    {
        id: "YS-01-129",
        name: "PRODUCT YS-01",
        price: 200,
        image: "/assets/extracted/images/img_129_YS-01_129.webp",
        category: "MENS",
    },
    {
        id: "HD-01-131",
        name: "HOODIE HD-01",
        price: 200,
        image: "/assets/extracted/images/img_131_HD-01_131.webp",
        category: "MENS",
    },
    {
        id: "PT-04-133",
        name: "PANTS PT-04",
        price: 300,
        image: "/assets/extracted/images/img_133_PT-04_133.webp",
        category: "MENS",
    },
    {
        id: "BT-01-135",
        name: "BOOT BT-01",
        price: 300,
        image: "/assets/extracted/images/img_135_BT-01_135.webp",
        category: "ACCESSORIES",
    },
    {
        id: "HD-01-137",
        name: "HOODIE HD-01",
        price: 220,
        image: "/assets/extracted/images/img_137_HD-01_137.webp",
        category: "MENS",
    },
    {
        id: "HD-01-139",
        name: "HOODIE HD-01",
        price: 220,
        image: "/assets/extracted/images/img_139_HD-01_139.webp",
        category: "MENS",
    },
    {
        id: "BP-02-13",
        name: "BACKPACK BP-02",
        price: 200,
        image: "/assets/extracted/images/img_13_BP-02_13.webp",
        category: "ACCESSORIES",
    },
    {
        id: "JC-05-141",
        name: "JACKET JC-05",
        price: 600,
        image: "/assets/extracted/images/img_141_JC-05_141.webp",
        category: "MENS",
    },
    {
        id: "YS-01-143",
        name: "PRODUCT YS-01",
        price: 200,
        image: "/assets/extracted/images/img_143_YS-01_143.webp",
        category: "MENS",
    },
    {
        id: "TS-01-145",
        name: "T-SHIRT TS-01",
        price: 110,
        image: "/assets/extracted/images/img_145_TS-01_145.webp",
        category: "MENS",
    },
    {
        id: "TS-02-147",
        name: "T-SHIRT TS-02",
        price: 130,
        image: "/assets/extracted/images/img_147_TS-02_147.webp",
        category: "MENS",
    },
    {
        id: "TS-04-149",
        name: "T-SHIRT TS-04",
        price: 160,
        image: "/assets/extracted/images/img_149_TS-04_149.webp",
        category: "MENS",
    },
    {
        id: "TT-02-151",
        name: "TOP TT-02",
        price: 130,
        image: "/assets/extracted/images/img_151_TT-02_151.webp",
        category: "WOMENS",
    },
    {
        id: "TT-04-153",
        name: "TOP TT-04",
        price: 180,
        image: "/assets/extracted/images/img_153_TT-04_153.webp",
        category: "WOMENS",
    },
    {
        id: "BD-03-155",
        name: "BODYSUIT BD-03",
        price: 200,
        image: "/assets/extracted/images/img_155_BD-03_155.webp",
        category: "WOMENS",
    },
    {
        id: "BD-04-157",
        name: "BODYSUIT BD-04",
        price: 200,
        image: "/assets/extracted/images/img_157_BD-04_157.webp",
        category: "WOMENS",
    },
    {
        id: "LS-04-159",
        name: "LONG SLEEVE LS-04",
        price: 200,
        image: "/assets/extracted/images/img_159_LS-04_159.webp",
        category: "MENS",
    },
    {
        id: "PK-01-15",
        name: "PARKA PK-01",
        price: 780,
        image: "/assets/extracted/images/img_15_PK-01_15.webp",
        category: "MENS",
    },
    {
        id: "HD-02-161",
        name: "HOODIE HD-02",
        price: 180,
        image: "/assets/extracted/images/img_161_HD-02_161.webp",
        category: "MENS",
    },
    {
        id: "HD-03-163",
        name: "HOODIE HD-03",
        price: 250,
        image: "/assets/extracted/images/img_163_HD-03_163.webp",
        category: "MENS",
    },
    {
        id: "JC-01-165",
        name: "JACKET JC-01",
        price: 600,
        image: "/assets/extracted/images/img_165_JC-01_165.webp",
        category: "MENS",
    },
    {
        id: "WB-01-167",
        name: "PRODUCT WB-01",
        price: 200,
        image: "/assets/extracted/images/img_167_WB-01_167.webp",
        category: "MENS",
    },
    {
        id: "BR-09-169",
        name: "BRA BR-09",
        price: 200,
        image: "/assets/extracted/images/img_169_BR-09_169.webp",
        category: "WOMENS",
    },
    {
        id: "SH-01-171",
        name: "SHIRT SH-01",
        price: 160,
        image: "/assets/extracted/images/img_171_SH-01_171.webp",
        category: "MENS",
    },
    {
        id: "SH-06-173",
        name: "SHIRT SH-06",
        price: 180,
        image: "/assets/extracted/images/img_173_SH-06_173.webp",
        category: "MENS",
    },
    {
        id: "PT-03-175",
        name: "PANTS PT-03",
        price: 250,
        image: "/assets/extracted/images/img_175_PT-03_175.webp",
        category: "MENS",
    },
    {
        id: "SP-01-177",
        name: "PRODUCT SP-01",
        price: 200,
        image: "/assets/extracted/images/img_177_SP-01_177.webp",
        category: "MENS",
    },
    {
        id: "SP-06-179",
        name: "PRODUCT SP-06",
        price: 200,
        image: "/assets/extracted/images/img_179_SP-06_179.webp",
        category: "MENS",
    },
    {
        id: "WD-02-17",
        name: "WINDBREAKER WD-02",
        price: 200,
        image: "/assets/extracted/images/img_17_WD-02_17.webp",
        category: "MENS",
    },
    {
        id: "LG-01-181",
        name: "LEGGINGS LG-01",
        price: 230,
        image: "/assets/extracted/images/img_181_LG-01_181.webp",
        category: "WOMENS",
    },
    {
        id: "LG-04-183",
        name: "LEGGINGS LG-04",
        price: 290,
        image: "/assets/extracted/images/img_183_LG-04_183.webp",
        category: "WOMENS",
    },
    {
        id: "LG-13-185",
        name: "LEGGINGS LG-13",
        price: 240,
        image: "/assets/extracted/images/img_185_LG-13_185.webp",
        category: "WOMENS",
    },
    {
        id: "UW-02-187",
        name: "PRODUCT UW-02",
        price: 200,
        image: "/assets/extracted/images/img_187_UW-02_187.webp",
        category: "MENS",
    },
    {
        id: "SK-01-189",
        name: "SNEAKER SK-01",
        price: 200,
        image: "/assets/extracted/images/img_189_SK-01_189.webp",
        category: "MENS",
    },
    {
        id: "SL-01-191",
        name: "SLIDES SL-01",
        price: 70,
        image: "/assets/extracted/images/img_191_SL-01_191.webp",
        category: "ACCESSORIES",
    },
    {
        id: "SL-02-193",
        name: "SLIDES SL-02",
        price: 70,
        image: "/assets/extracted/images/img_193_SL-02_193.webp",
        category: "ACCESSORIES",
    },
    {
        id: "HL-01-195",
        name: "PRODUCT HL-01",
        price: 200,
        image: "/assets/extracted/images/img_195_HL-01_195.webp",
        category: "MENS",
    },
    {
        id: "HL-02-197",
        name: "PRODUCT HL-02",
        price: 200,
        image: "/assets/extracted/images/img_197_HL-02_197.webp",
        category: "MENS",
    },
    {
        id: "HL-03-199",
        name: "PRODUCT HL-03",
        price: 200,
        image: "/assets/extracted/images/img_199_HL-03_199.webp",
        category: "MENS",
    },
    {
        id: "SL-01-19",
        name: "SLIDES SL-01",
        price: 70,
        image: "/assets/extracted/images/img_19_SL-01_19.webp",
        category: "ACCESSORIES",
    },
    {
        id: "PK-01-1",
        name: "PARKA PK-01",
        price: 520,
        image: "/assets/extracted/images/img_1_PK-01_1.webp",
        category: "MENS",
    },
    {
        id: "HB-01-201",
        name: "PRODUCT HB-01",
        price: 200,
        image: "/assets/extracted/images/img_201_HB-01_201.webp",
        category: "MENS",
    },
    {
        id: "PD-01-203",
        name: "PRODUCT PD-01",
        price: 200,
        image: "/assets/extracted/images/img_203_PD-01_203.webp",
        category: "MENS",
    },
    {
        id: "HT-01-205",
        name: "HAT HT-01",
        price: 200,
        image: "/assets/extracted/images/img_205_HT-01_205.webp",
        category: "ACCESSORIES",
    },
    {
        id: "SG-01-207",
        name: "PRODUCT SG-01",
        price: 200,
        image: "/assets/extracted/images/img_207_SG-01_207.webp",
        category: "MENS",
    },
    {
        id: "SG-02-209",
        name: "PRODUCT SG-02",
        price: 200,
        image: "/assets/extracted/images/img_209_SG-02_209.webp",
        category: "MENS",
    },
    {
        id: "BP-01-211",
        name: "BACKPACK BP-01",
        price: 200,
        image: "/assets/extracted/images/img_211_BP-01_211.webp",
        category: "ACCESSORIES",
    },
    {
        id: "JC-03-213",
        name: "JACKET JC-03",
        price: 700,
        image: "/assets/extracted/images/img_213_JC-03_213.webp",
        category: "MENS",
    },
    {
        id: "TS-05-215",
        name: "T-SHIRT TS-05",
        price: 190,
        image: "/assets/extracted/images/img_215_TS-05_215.webp",
        category: "MENS",
    },
    {
        id: "TS-01-217",
        name: "T-SHIRT TS-01",
        price: 180,
        image: "/assets/extracted/images/img_217_TS-01_217.webp",
        category: "MENS",
    },
    {
        id: "WB-01-219",
        name: "PRODUCT WB-01",
        price: 200,
        image: "/assets/extracted/images/img_219_WB-01_219.webp",
        category: "MENS",
    },
    {
        id: "CT-01-21",
        name: "COAT CT-01",
        price: 750,
        image: "/assets/extracted/images/img_21_CT-01_21.webp",
        category: "WOMENS",
    },
    {
        id: "SH-01-221",
        name: "SHIRT SH-01",
        price: 120,
        image: "/assets/extracted/images/img_221_SH-01_221.webp",
        category: "MENS",
    },
    {
        id: "SP-08-223",
        name: "PRODUCT SP-08",
        price: 200,
        image: "/assets/extracted/images/img_223_SP-08_223.webp",
        category: "MENS",
    },
    {
        id: "SP-09-225",
        name: "PRODUCT SP-09",
        price: 200,
        image: "/assets/extracted/images/img_225_SP-09_225.webp",
        category: "MENS",
    },
    {
        id: "SK-01-227",
        name: "SNEAKER SK-01",
        price: 200,
        image: "/assets/extracted/images/img_227_SK-01_227.webp",
        category: "MENS",
    },
    {
        id: "HD-10-229",
        name: "HOODIE HD-10",
        price: 220,
        image: "/assets/extracted/images/img_229_HD-10_229.webp",
        category: "MENS",
    },
    {
        id: "TS-01-231",
        name: "T-SHIRT TS-01",
        price: 130,
        image: "/assets/extracted/images/img_231_TS-01_231.webp",
        category: "MENS",
    },
    {
        id: "TS-02-233",
        name: "T-SHIRT TS-02",
        price: 100,
        image: "/assets/extracted/images/img_233_TS-02_233.webp",
        category: "MENS",
    },
    {
        id: "SP-01-235",
        name: "PRODUCT SP-01",
        price: 200,
        image: "/assets/extracted/images/img_235_SP-01_235.webp",
        category: "MENS",
    },
    {
        id: "SP-06-237",
        name: "PRODUCT SP-06",
        price: 200,
        image: "/assets/extracted/images/img_237_SP-06_237.webp",
        category: "MENS",
    },
    {
        id: "SK-01-239",
        name: "SNEAKER SK-01",
        price: 200,
        image: "/assets/extracted/images/img_239_SK-01_239.webp",
        category: "MENS",
    },
    {
        id: "BG-03-23",
        name: "BAG BG-03",
        price: 200,
        image: "/assets/extracted/images/img_23_BG-03_23.webp",
        category: "ACCESSORIES",
    },
    {
        id: "TS-07-25",
        name: "T-SHIRT TS-07",
        price: 110,
        image: "/assets/extracted/images/img_25_TS-07_25.webp",
        category: "MENS",
    },
    {
        id: "LS-03-27",
        name: "LONG SLEEVE LS-03",
        price: 200,
        image: "/assets/extracted/images/img_27_LS-03_27.webp",
        category: "MENS",
    },
    {
        id: "SL-01-29",
        name: "SLIDES SL-01",
        price: 70,
        image: "/assets/extracted/images/img_29_SL-01_29.webp",
        category: "ACCESSORIES",
    },
    {
        id: "RC-04-31",
        name: "RAIN COAT RC-04",
        price: 520,
        image: "/assets/extracted/images/img_31_RC-04_31.webp",
        category: "WOMENS",
    },
    {
        id: "WP-02-33",
        name: "PANTS WP-02",
        price: 270,
        image: "/assets/extracted/images/img_33_WP-02_33.webp",
        category: "MENS",
    },
    {
        id: "JC-07-35",
        name: "JACKET JC-07",
        price: 540,
        image: "/assets/extracted/images/img_35_JC-07_35.webp",
        category: "MENS",
    },
    {
        id: "JC-09-37",
        name: "JACKET JC-09",
        price: 750,
        image: "/assets/extracted/images/img_37_JC-09_37.webp",
        category: "MENS",
    },
    {
        id: "BB-02-39",
        name: "BUBBLE JACKET BB-02",
        price: 790,
        image: "/assets/extracted/images/img_39_BB-02_39.webp",
        category: "WOMENS",
    },
    {
        id: "JC-10-3",
        name: "JACKET JC-10",
        price: 700,
        image: "/assets/extracted/images/img_3_JC-10_3.webp",
        category: "MENS",
    },
    {
        id: "RC-03-41",
        name: "RAIN COAT RC-03",
        price: 560,
        image: "/assets/extracted/images/img_41_RC-03_41.webp",
        category: "WOMENS",
    },
    {
        id: "WD-01-43",
        name: "WINDBREAKER WD-01",
        price: 200,
        image: "/assets/extracted/images/img_43_WD-01_43.webp",
        category: "MENS",
    },
    {
        id: "WP-01-45",
        name: "PANTS WP-01",
        price: 220,
        image: "/assets/extracted/images/img_45_WP-01_45.webp",
        category: "MENS",
    },
    {
        id: "WB-04-47",
        name: "PRODUCT WB-04",
        price: 200,
        image: "/assets/extracted/images/img_47_WB-04_47.webp",
        category: "MENS",
    },
    {
        id: "BB-01-49",
        name: "BUBBLE JACKET BB-01",
        price: 700,
        image: "/assets/extracted/images/img_49_BB-01_49.webp",
        category: "WOMENS",
    },
    {
        id: "JC-04-51",
        name: "JACKET JC-04",
        price: 630,
        image: "/assets/extracted/images/img_51_JC-04_51.webp",
        category: "MENS",
    },
    {
        id: "WB-04-53",
        name: "PRODUCT WB-04",
        price: 200,
        image: "/assets/extracted/images/img_53_WB-04_53.webp",
        category: "MENS",
    },
    {
        id: "BB-01-55",
        name: "BUBBLE JACKET BB-01",
        price: 770,
        image: "/assets/extracted/images/img_55_BB-01_55.webp",
        category: "WOMENS",
    },
    {
        id: "HD-04-57",
        name: "HOODIE HD-04",
        price: 260,
        image: "/assets/extracted/images/img_57_HD-04_57.webp",
        category: "MENS",
    },
    {
        id: "BB-01-59",
        name: "BUBBLE JACKET BB-01",
        price: 780,
        image: "/assets/extracted/images/img_59_BB-01_59.webp",
        category: "WOMENS",
    },
    {
        id: "JC-11-5",
        name: "JACKET JC-11",
        price: 640,
        image: "/assets/extracted/images/img_5_JC-11_5.webp",
        category: "MENS",
    },
    {
        id: "HD-04-61",
        name: "HOODIE HD-04",
        price: 180,
        image: "/assets/extracted/images/img_61_HD-04_61.webp",
        category: "MENS",
    },
    {
        id: "JC-09-63",
        name: "JACKET JC-09",
        price: 710,
        image: "/assets/extracted/images/img_63_JC-09_63.webp",
        category: "MENS",
    },
    {
        id: "WP-01-65",
        name: "PANTS WP-01",
        price: 260,
        image: "/assets/extracted/images/img_65_WP-01_65.webp",
        category: "MENS",
    },
    {
        id: "WD-01-67",
        name: "WINDBREAKER WD-01",
        price: 200,
        image: "/assets/extracted/images/img_67_WD-01_67.webp",
        category: "MENS",
    },
    {
        id: "TS-03-69",
        name: "T-SHIRT TS-03",
        price: 160,
        image: "/assets/extracted/images/img_69_TS-03_69.webp",
        category: "MENS",
    },
    {
        id: "TS-03-71",
        name: "T-SHIRT TS-03",
        price: 180,
        image: "/assets/extracted/images/img_71_TS-03_71.webp",
        category: "MENS",
    },
    {
        id: "TS-03-73",
        name: "T-SHIRT TS-03",
        price: 170,
        image: "/assets/extracted/images/img_73_TS-03_73.webp",
        category: "MENS",
    },
    {
        id: "TS-07-75",
        name: "T-SHIRT TS-07",
        price: 120,
        image: "/assets/extracted/images/img_75_TS-07_75.webp",
        category: "MENS",
    },
    {
        id: "TT-06-77",
        name: "TOP TT-06",
        price: 120,
        image: "/assets/extracted/images/img_77_TT-06_77.webp",
        category: "WOMENS",
    },
    {
        id: "LS-03-79",
        name: "LONG SLEEVE LS-03",
        price: 200,
        image: "/assets/extracted/images/img_79_LS-03_79.webp",
        category: "MENS",
    },
    {
        id: "SL-03-7",
        name: "SLIDES SL-03",
        price: 70,
        image: "/assets/extracted/images/img_7_SL-03_7.webp",
        category: "ACCESSORIES",
    },
    {
        id: "HD-10-81",
        name: "HOODIE HD-10",
        price: 250,
        image: "/assets/extracted/images/img_81_HD-10_81.webp",
        category: "MENS",
    },
    {
        id: "JC-08-83",
        name: "JACKET JC-08",
        price: 570,
        image: "/assets/extracted/images/img_83_JC-08_83.webp",
        category: "MENS",
    },
    {
        id: "JC-08-85",
        name: "JACKET JC-08",
        price: 510,
        image: "/assets/extracted/images/img_85_JC-08_85.webp",
        category: "MENS",
    },
    {
        id: "PK-01-87",
        name: "PARKA PK-01",
        price: 600,
        image: "/assets/extracted/images/img_87_PK-01_87.webp",
        category: "MENS",
    },
    {
        id: "HT-05-89",
        name: "HAT HT-05",
        price: 200,
        image: "/assets/extracted/images/img_89_HT-05_89.webp",
        category: "ACCESSORIES",
    },
    {
        id: "BG-02-91",
        name: "BAG BG-02",
        price: 200,
        image: "/assets/extracted/images/img_91_BG-02_91.webp",
        category: "ACCESSORIES",
    },
    {
        id: "GL-01-93",
        name: "GLOVES GL-01",
        price: 200,
        image: "/assets/extracted/images/img_93_GL-01_93.webp",
        category: "ACCESSORIES",
    },
    {
        id: "YS-01-95",
        name: "PRODUCT YS-01",
        price: 200,
        image: "/assets/extracted/images/img_95_YS-01_95.webp",
        category: "MENS",
    },
    {
        id: "YS-01-97",
        name: "PRODUCT YS-01",
        price: 200,
        image: "/assets/extracted/images/img_97_YS-01_97.webp",
        category: "MENS",
    },
    {
        id: "YS-01-99",
        name: "PRODUCT YS-01",
        price: 200,
        image: "/assets/extracted/images/img_99_YS-01_99.webp",
        category: "MENS",
    },
    {
        id: "BL-01-9",
        name: "BLANKET BL-01",
        price: 200,
        image: "/assets/extracted/images/img_9_BL-01_9.webp",
        category: "ACCESSORIES",
    },
];
